// <auto-generated>
//     This code was generated by GitHub Copilot to represent monkey species data.
// </auto-generated>

namespace MyMonkeyApp;

/// <summary>
/// Represents a monkey with descriptive information and geographic data.
/// </summary>
public sealed class Monkey
{
    /// <summary>
    /// Gets or sets the common name of the monkey.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the primary geographic location or region where the monkey is found.
    /// </summary>
    public string Location { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets additional details describing the monkey.
    /// </summary>
    public string Details { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets a URL pointing to an image representing the monkey.
    /// </summary>
    public string Image { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the estimated population count.
    /// </summary>
    public int Population { get; set; }

    /// <summary>
    /// Gets or sets the latitude coordinate for the monkey's representative location.
    /// </summary>
    public double Latitude { get; set; }

    /// <summary>
    /// Gets or sets the longitude coordinate for the monkey's representative location.
    /// </summary>
    public double Longitude { get; set; }

    /// <summary>
    /// Returns a readable string representation of the monkey.
    /// </summary>
    public override string ToString() => $"{Name} — {Location} (Pop: {Population:N0})";
}
